In [1]:
import numpy as np

## Define Matrix as numpy Array

In [80]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
xones=np.ones((2,3), dtype=int)
np.arange(5)

array([0, 1, 2, 3, 4])

In [78]:
print x
print x.shape
print xones
print xones.shape

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 1 1]
 [1 1 1]]
(2, 3)


In [7]:
type(x)

numpy.ndarray

## Access Matrix Element; Rows; Columns

In [93]:
print x[0][1], x[0][0]

2 1


In [95]:
print x[:, 0]

[1 4]


In [96]:
print x[0, :]

[1 2 3]


## Matrix Operation: Multiplication, Sum etc.

In [60]:
a = np.array([[0, 1, 0, 0], [0, 0, 0, 1]])
b = np.random.rand(4,2)
d = np.random.rand(4,2)

In [61]:
print b
print a
print d

[[0.86593245 0.12649878]
 [0.17876212 0.02827202]
 [0.68293838 0.28819789]
 [0.69822676 0.83704905]]
[[0 1 0 0]
 [0 0 0 1]]
[[0.89413591 0.63442126]
 [0.29848578 0.97390821]
 [0.57969742 0.61497292]
 [0.0644056  0.46680487]]


### Matrix Summation

In [62]:
b+d

array([[1.76006835, 0.76092004],
       [0.47724789, 1.00218022],
       [1.2626358 , 0.90317081],
       [0.76263236, 1.30385392]])

### Matrix multiplication

In [41]:
print np.matmul(a, b)

[[0.99777829 0.77799387]
 [0.71207617 0.19897411]]


In [45]:
print 2*b

[[1.7874359  1.07267301]
 [1.99555657 1.55598774]
 [0.8787603  0.86389729]
 [1.42415234 0.39794823]]


### Element-wise multiplication

In [83]:
c = np.array([[1, 1],[2, 2], [3, 3], [4, 4]])
print np.multiply(c, b)
print c*b

[[0.86593245 0.12649878]
 [0.35752423 0.05654403]
 [2.04881514 0.86459367]
 [2.79290703 3.34819618]]
[[0.86593245 0.12649878]
 [0.35752423 0.05654403]
 [2.04881514 0.86459367]
 [2.79290703 3.34819618]]


### Dot product

In [54]:
v1 = np.array([1, 2, 3, 1])
v2 = np.array([1, 0, 1, 0])

In [55]:
np.dot(v1, v2)

4

In [63]:
np.matmul(v1, v2.T) #v2.T is the transpose of vector v2

4

## Other Useful Operations

In [70]:
print c.size
print c.shape

8
(4, 2)


In [72]:
cprime=c.reshape(2,4)
print cprime

[[1 1 2 2]
 [3 3 4 4]]


In [74]:
print cprime.shape

(2, 4)


## Matrix Analysis Example

In [110]:
M = np.random.rand(5,5)

In [111]:
print np.mean(M[0])
print np.mean(M[1])
print np.mean(M)

0.7362946342890464
0.7198752672367307
0.6320102166335464


In [112]:
from numpy.linalg import inv

In [113]:
np.matmul(inv(M), M)

array([[ 1.00000000e+00,  2.91705531e-15,  3.74587673e-15,
         2.01298060e-15,  2.99495715e-15],
       [-2.47393892e-15,  1.00000000e+00, -2.35584257e-15,
        -1.17119363e-15, -1.56691262e-15],
       [-1.21700681e-15, -4.18731488e-16,  1.00000000e+00,
        -9.66783982e-16, -4.51598464e-16],
       [ 3.25293091e-16,  4.86059573e-18,  4.83882894e-16,
         1.00000000e+00, -2.13763774e-16],
       [ 3.17111491e-16,  4.34056908e-17,  3.48878928e-16,
         2.23333994e-16,  1.00000000e+00]])