In [1]:
import numpy as np

## Define Matrix as numpy Array

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [3]:
print(x)

[[1 2 3]
 [4 5 6]]


In [4]:
xones=np.ones((2,3), dtype=int)

In [5]:
print(xones)

[[1 1 1]
 [1 1 1]]


In [6]:
type(x)

numpy.ndarray

In [ ]:
type(list(x))

In [10]:
M100=np.arange(100).reshape(10, 10)

In [11]:
print(x.shape)

(2, 3)


In [14]:
print (np.arange(100).shape)

(100,)


In [ ]:
print xones
print xones.shape

## Access Matrix Element; Rows; Columns

In [15]:
print(x[0][1], x[0][0])

(2, 1)


In [18]:
print(x[:, 0].shape)

(2,)


In [19]:
print (x[0, :].shape)

(3,)


## Matrix Operation: Multiplication, Sum etc.

In [20]:
b = np.random.rand(4,2)
d = np.random.rand(4,2)

In [25]:
print b
print d

[[0.43564525 0.09141664]
 [0.73779738 0.38693437]
 [0.20661604 0.71344531]
 [0.07856274 0.06303989]]
[[0.8828034  0.60603865]
 [0.55474195 0.8782398 ]
 [0.37707209 0.73080502]
 [0.48365092 0.17211151]]


In [23]:
a = np.array([[0, 1, 0, 0], [0, 0, 0, 1]])

### Matrix Summation

In [24]:
b+d

array([[1.31844864, 0.69745529],
       [1.29253933, 1.26517417],
       [0.58368813, 1.44425033],
       [0.56221366, 0.23515141]])

### Matrix multiplication

In [30]:
print ("b:")
print(b)
print ("after multiplication")
print np.matmul(a, b)

b:
[[0.43564525 0.09141664]
 [0.73779738 0.38693437]
 [0.20661604 0.71344531]
 [0.07856274 0.06303989]]
after multiplication
[[0.73779738 0.38693437]
 [0.07856274 0.06303989]]


In [33]:
b[1, :]

array([0.73779738, 0.38693437])

In [ ]:
print 2*b

### Element-wise multiplication

In [34]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [35]:
print np.multiply(x, x)

[[ 1  4  9]
 [16 25 36]]


### Dot product

In [37]:
v1 = np.array([1, 2, 3, 1])
v2 = np.array([1, 0, 1, 0])

In [39]:
np.dot(v1, v1)

15

In [40]:
np.matmul(v1, v1.T) #v2.T is the transpose of vector v2

15

## Other Useful Operations

In [42]:
print x.size

6


In [ ]:
print cprime.shape

## Matrix Analysis Example

In [ ]:
M = np.random.randn(5,5)

SyntaxError: invalid syntax (<ipython-input-2-56faa33c6007>, line 2)

In [ ]:
print np.mean(M[0])
print np.mean(M[1])
print np.mean(M)

In [ ]:
from numpy.linalg import inv

In [ ]:
np.matmul(inv(M), M)