## Install packages for this session

```pip install numpy```

or

```pip3 install numpy```

In [2]:
import numpy as np #import numpy as package and refer it as np in code

## 1. Create Matrices

### Create Matrices from List
- Use list as the basic datatype [[1, 2, 3], [4, 5, 6]]
- Initialize a matrix using np.array()

In [4]:
createlist4matrix=[[1, 2, 3], [4, 5, 6]]

In [5]:
x = np.array(createlist4matrix)

In [6]:
print(x)
print(type(x))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### Create Special Matrix

#### Create a 2x3 matrix of all ones

In [12]:
xones=np.ones((2,3))

In [11]:
print(xones)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Create a 1x100 matrix numbered between 0 and 99

In [15]:
M100=np.arange(100)

In [16]:
print(M100)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [17]:
print(M100.shape)

(100,)


#### Create a matrix by reshaping from an existing matrix/vector

In [24]:
M10_10=M100.reshape(10, 10)

In [25]:
print(M10_10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### Create a matrix using random numbers of uniform distribution between [0, 1)

In [47]:
m_uniform = np.random.rand(4,2)
print(m_uniform)

[[0.96694386 0.4390844 ]
 [0.81607029 0.74170795]
 [0.84351969 0.55791591]
 [0.02716553 0.28217551]]


## 2. Access Matrix Elements; Rows; Columns

#### get the ith row and jth column elements; syntax ```m[i][j]```, i and j starts from 0

In [111]:
m=np.arange(36).reshape(6,6)
print(m)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [33]:
print(m[5][5])

35


#### get the jth column from matrix m; syntax ```m[:, j]```

In [39]:
print(m[:, 1])

[ 1  7 13 19 25 31]


#### get the ith row from matrix m; syntax ```m[i, :]```

In [42]:
print (m[0, :])

[0 1 2 3 4 5]


## 3. Matrix Operation: Multiplication, Sum etc.

In [53]:
b = np.random.rand(4,2)
d = np.random.rand(4,2)

In [54]:
print(b)
print(d)

[[0.48051297 0.59863922]
 [0.57609378 0.95176081]
 [0.13672047 0.25217784]
 [0.17413099 0.43842167]]
[[0.81813997 0.21463446]
 [0.43543558 0.03007659]
 [0.1175277  0.53971906]
 [0.06941771 0.92864161]]


### Matrix Summation

In [55]:
b+d

array([[1.29865295, 0.81327367],
       [1.01152936, 0.9818374 ],
       [0.25424817, 0.7918969 ],
       [0.24354871, 1.36706328]])

### Matrix multiplication

#### Standard matrix multiplication
\begin{equation}
A_{mxn}=\begin{bmatrix}a_{1,1} & a_{1,2} & \dots & a_{1,n}   \\ a_{2,1} & a_{2,2} & \dots & \dots   \\      a_{3,1} & a_{3,2} & \ddots & \dots  \\      a_{m,1}  & \vdots  & \vdots & a_{m,n}     
\end{bmatrix}  
\end{equation}
\begin{equation}
B_{nxp} = \begin{bmatrix}      b_{1,1} & b_{1,2} & \dots & b_{1,p}   \\       b_{2,1} & b_{2,2} & \dots & \dots   \\      b_{3,1} & b_{3,2} & \ddots & \dots  \\     b_{n,1}  & \vdots  & \vdots & b_{n,p}     
\end{bmatrix}
\end{equation}
\begin{equation}
AB = \begin{bmatrix}      a_{1,1}b_{1,1} + a_{1,2}b_{2,1} + \dots + a_{1,n}b_{n,1} & \dots  \\       \vdots & a_{m,1}b_{1,p} + a_{m,2}b_{2,p} + \dots + a_{m,n}b_{n,p}     \end{bmatrix}
\end{equation}


In [60]:
print(np.matmul(b, d.T))

[[0.52161547 0.22723747 0.37957058 0.5892774 ]
 [0.67560601 0.27947745 0.58139043 0.9238358 ]
 [0.16598254 0.06711761 0.15217363 0.24367366]
 [0.23656392 0.08900906 0.25708975 0.41922438]]


In [67]:
i=1
j=2
np.matmul(b[i,:], d.T[:,j]) #ith row, jth column element in the outcome

0.5813904282881497

#### Alternative way to get the jth column from matrix 
#### using a selection matrix
\begin{equation}
m_{sel}=
\begin{bmatrix}
0\\
0\\
\vdots\\
\underbrace{1}_{j_{th} \text{ row}}\\
\vdots\\
0
\end{bmatrix}
\end{equation}
#### The $j_{th}$ column of matrix $m$ can be selected by matrix multiplication $$m[:,j]=mm_{sel}$$

In [116]:
m_sel=np.zeros(6)
m_sel[j]=1
print(m_sel)

[0. 1. 0. 0. 0. 0.]


In [114]:
np.matmul(m, m_sel.reshape(6,1))

array([[ 1.],
       [ 7.],
       [13.],
       [19.],
       [25.],
       [31.]])

#### Alternative way to get the ith row from matrix m:
#### using a selection matrix
\begin{equation}
m_{sel}=
\begin{bmatrix}
0, 0, \cdots,{\underbrace{1}_{i_{th} \text{ column}}}, \cdots, 0
\end{bmatrix}
\end{equation}

#### The $i_{th}$ row of matrix $m$ can be selected by matrix multiplication $$m[i,:]=m_{sel}m $$

In [130]:
i=0
m_sel=np.zeros(6)
m_sel[i]=1
print(m_sel)

[1. 0. 0. 0. 0. 0.]


In [131]:
np.matmul(m_sel.reshape(1,6), m)

array([[0., 1., 2., 3., 4., 5.]])

#### Matrix multiply by a constant

In [64]:
2*b

array([[0.96102595, 1.19727844],
       [1.15218756, 1.90352162],
       [0.27344094, 0.50435569],
       [0.34826198, 0.87684334]])

#### Element-by-element multiplication

In [66]:
print(np.multiply(b, d))

[[0.39312687 0.1284886 ]
 [0.25085173 0.02862572]
 [0.01606844 0.13610519]
 [0.01208778 0.4071366 ]]


In [73]:
i=1
j=1
(b[i][j]*d[i][j]) #ith row, jth column element in the outcome

0.02862571947980738

### Dot Product for Vector

In [92]:
v1 = np.array([1, 2, 3, 1])
v2 = np.array([0, 0, 1, 0])

In [97]:
np.dot(v1, v2)

3

In [99]:
np.matmul(v1, v1.T) #v2.T is the transpose of vector v2

15

In [86]:
m=np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [96]:
np.matmul(m,v2)

array([ 2,  6, 10, 14])

## Other Useful Operations

In [ ]:
print x.size

In [ ]:
print cprime.shape

## Matrix Inverse

In [ ]:
from numpy.linalg import inv

In [ ]:
np.matmul(inv(M), M)