# Matrix, Vector, Linear Algerbra 
### Topics: Use numpy to define matrix, matrix multiplication, dot product, inverse of matrix

```Install packages for this session```

```pip install numpy``` or

```pip3 install numpy``` 

In [2]:
import numpy as np #import numpy as package and refer it as np in code

## 1. Create Matrices

### Create Matrices from List
- Use list as the basic datatype [[1, 2, 3], [4, 5, 6]]
- Initialize a matrix using np.array()

In [4]:
createlist4matrix=[[1, 2, 3], [4, 5, 6]]

In [5]:
x = np.array(createlist4matrix)

In [6]:
print(x)
print(type(x))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### Create Special Matrix

#### Create a 2x3 matrix of all ones

In [12]:
xones=np.ones((2,3))

In [11]:
print(xones)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Create a 1x100 matrix numbered between 0 and 99

In [15]:
M100=np.arange(100)

In [16]:
print(M100)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [17]:
print(M100.shape)

(100,)


#### Create a matrix by reshaping from an existing matrix/vector

In [24]:
M10_10=M100.reshape(10, 10)

In [25]:
print(M10_10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### Create a matrix using random numbers of uniform distribution between [0, 1)

In [47]:
m_uniform = np.random.rand(4,2)
print(m_uniform)

[[0.96694386 0.4390844 ]
 [0.81607029 0.74170795]
 [0.84351969 0.55791591]
 [0.02716553 0.28217551]]


## 2. Access Matrix Elements; Rows; Columns

#### get the ith row and jth column elements; syntax ```m[i][j]```, i and j starts from 0

In [19]:
m=np.arange(36).reshape(6,6)
print(m)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [20]:
print(m[5][5])

35


#### get the jth column from matrix m; syntax ```m[:, j]```

In [21]:
print(m[:, 1])

[ 1  7 13 19 25 31]


#### get the ith row from matrix m; syntax ```m[i, :]```

In [22]:
print (m[0, :])

[0 1 2 3 4 5]


## 3. Matrix Operation: Multiplication, Sum etc.

In [23]:
A = np.random.rand(4,2)
B = np.random.rand(4,2)

In [24]:
print(A)
print(B)

[[0.61295755 0.81983441]
 [0.78386886 0.13947352]
 [0.4496694  0.71810273]
 [0.95697089 0.73306867]]
[[0.22722313 0.14175761]
 [0.6731217  0.70893443]
 [0.34246002 0.52451024]
 [0.31464447 0.12978747]]


### Matrix Summation

In [25]:
A+B

array([[0.84018069, 0.96159202],
       [1.45699057, 0.84840794],
       [0.79212942, 1.24261297],
       [1.27161537, 0.86285614]])

### Matrix multiplication

#### Standard matrix multiplication
\begin{equation}
A_{mxn}=\begin{bmatrix}a_{1,1} & a_{1,2} & \dots & a_{1,n}   \\ a_{2,1} & a_{2,2} & \dots & \dots   \\      a_{3,1} & a_{3,2} & \ddots & \dots  \\      a_{m,1}  & \vdots  & \vdots & a_{m,n}     
\end{bmatrix}  
\end{equation}
\begin{equation}
B_{nxp} = \begin{bmatrix}      b_{1,1} & b_{1,2} & \dots & b_{1,p}   \\       b_{2,1} & b_{2,2} & \dots & \dots   \\      b_{3,1} & b_{3,2} & \ddots & \dots  \\     b_{n,1}  & \vdots  & \vdots & b_{n,p}     
\end{bmatrix}
\end{equation}
\begin{equation}
AB = \begin{bmatrix}      a_{1,1}b_{1,1} + a_{1,2}b_{2,1} + \dots + a_{1,n}b_{n,1} & \dots  \\       \vdots & a_{m,1}b_{1,p} + a_{m,2}b_{2,p} + \dots + a_{m,n}b_{n,p}     \end{bmatrix}
\end{equation}


In [27]:
print(np.matmul(A, B.T))

[[0.2554959  0.99380387 0.639925   0.29926794]
 [0.19788457 0.62651672 0.34159903 0.26474192]
 [0.20397181 0.81176998 0.53064603 0.23468673]
 [0.32136399 1.1638555  0.7122263  0.39624873]]


In [28]:
i=1
j=2
np.matmul(A[i,:], B.T[:,j]) #ith row, jth column element in the outcome

0.3415990311709295

#### Alternative way to get the jth column from matrix 
#### using a selection matrix
\begin{equation}
m_{sel}=
\begin{bmatrix}
0\\
0\\
\vdots\\
\underbrace{1}_{j_{th} \text{ row}}\\
\vdots\\
0
\end{bmatrix}
\end{equation}
#### The $j_{th}$ column of matrix $m$ can be selected by matrix multiplication $$m[:,j]=mm_{sel}$$

In [29]:
m_sel=np.zeros(6)
m_sel[j]=1
print(m_sel)

[0. 0. 1. 0. 0. 0.]


In [30]:
np.matmul(m, m_sel.reshape(6,1))

array([[ 2.],
       [ 8.],
       [14.],
       [20.],
       [26.],
       [32.]])

#### Alternative way to get the ith row from matrix m:
#### using a selection matrix
\begin{equation}
m_{sel}=
\begin{bmatrix}
0, 0, \cdots,{\underbrace{1}_{i_{th} \text{ column}}}, \cdots, 0
\end{bmatrix}
\end{equation}

#### The $i_{th}$ row of matrix $m$ can be selected by matrix multiplication $$m[i,:]=m_{sel}m $$

In [31]:
i=0
m_sel=np.zeros(6)
m_sel[i]=1
print(m_sel)

[1. 0. 0. 0. 0. 0.]


In [32]:
np.matmul(m_sel.reshape(1,6), m)

array([[0., 1., 2., 3., 4., 5.]])

#### Matrix multiply by a constant
\begin{equation}
cA_{mxn}=\begin{bmatrix}c a_{1,1} & c a_{1,2} & \dots & c a_{1,n}   \\ c a_{2,1} & c a_{2,2} & \dots & \dots   \\      c a_{3,1} & c a_{3,2} & \ddots & \dots  \\      c a_{m,1}  & \vdots  & \vdots & c a_{m,n}     
\end{bmatrix}  
\end{equation}


In [33]:
A = np.arange(16).reshape(4,4)

In [34]:
2*A

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

#### Element-by-element multiplication

#### Standard matrix multiplication
\begin{equation}
A_{mxn}=\begin{bmatrix}a_{1,1} & a_{1,2} & \dots & a_{1,n}   \\ a_{2,1} & a_{2,2} & \dots & \dots   \\      a_{3,1} & a_{3,2} & \ddots & \dots  \\      a_{m,1}  & \vdots  & \vdots & a_{m,n}     
\end{bmatrix}  
\end{equation}
\begin{equation}
B_{mxn} = \begin{bmatrix}      b_{1,1} & b_{1,2} & \dots & b_{1,n}   \\       b_{2,1} & b_{2,2} & \dots & \dots   \\      b_{3,1} & b_{3,2} & \ddots & \dots  \\     b_{m,1}  & \vdots  & \vdots & b_{m,n}     
\end{bmatrix}
\end{equation}

\begin{equation}
A_{mxn} \odot B_{mxn} = \begin{bmatrix}      a_{1,1}b_{1,1} & a_{1,2} b_{1,2} & \dots & a_{1,n}b_{1,n}   \\       a_{2,1}b_{2,1} & a_{2,2} b_{2,2} & \dots & \dots   \\      a_{3,1}b_{3,1} & a_{3,2}b_{3,2} & \ddots & \dots  \\     a_{m,1}b_{m,1}  & \vdots  & \vdots & a_{m,n}b_{m,n}     
\end{bmatrix}
\end{equation}

In [35]:
A = np.arange(16).reshape(4,4)
B = np.arange(16).reshape(4,4)

print(np.multiply(A, B))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [37]:
i=1
j=1
(A[i][j]*B[i][j]) #ith row, jth column element in the outcome

25

### 3. Dot Product for Vector
$\vec{v}\cdot\vec{w}=\sum\limits v_1w_1+v_2w_2+...v_nw_n$

In [38]:
v = np.array([1, 2, 3, 1])
w = np.array([0, 0, 1, 0])

In [39]:
np.dot(v, w)

3

In [41]:
np.matmul(v, w.T) #Alternative way of calculating dot product v2.T is the transpose of vector v2

3

In [42]:
m=np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## Other Useful Operations

In [ ]:
print x.size

In [ ]:
print cprime.shape

## Matrix Inverse
$M^{-1}M=I$

In [6]:
from numpy.linalg import inv

In [11]:
M = np.random.rand(2,2)

In [12]:
inv(M)

array([[ 7.85524429, -6.71851303],
       [-6.55822182,  6.80659039]])

In [13]:
np.matmul(inv(M), M)

array([[1.00000000e+00, 6.64041729e-16],
       [1.29401851e-16, 1.00000000e+00]])