# Lecture 04 - Logistic Regression

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

### Logistic Regression
#### Likelihood 
\begin{equation}
\ell=\log(L)={\sum_{i=1}^{n}y^i\log(p_i)+(1-y^i)\log(1-p_i)}
\end{equation}

#### Parameter model
\begin{equation}
p_i=\frac{1}{1+\exp\left(-(\beta_0+\beta_1x_1^i+\beta_2 x_2^i+...\beta_m x_m^i)\right)}
\end{equation}

### Synthesized Data  

In [ ]:
X1 = 2*np.random.randn(5000, 1)
X2 = 5*np.random.randn(5000, 1)
X3 = np.random.randn(5000, 1)

# p is calculated from predictors
eta=0.5*X1+0.1*X2+1.56*X3-1
X=np.column_stack([X1,X2, X3])
p=1/(1+np.exp(-eta))

y=np.random.binomial(1, p).reshape(5000,1)

In [ ]:
np.unique(y)

In [ ]:
plt.scatter(X[:,1], y)
plt.title('Scatter plot')
plt.xlabel('X2')
plt.ylabel('Label')
plt.show()

### Logistic Regression from Scratch

#### Hessian Matrix:
\begin{align*}
{{H}}={-X^TWX}, {W}=  
\begin{bmatrix}
   {p_1 (1-p_1)} & & \\
    & \ddots & \\
    & & {p_n (1-p_n)}
  \end{bmatrix}
\end{align*}

#### Iteratively Re-Weighted Least Squares
\begin{align*}
{\vec{\beta}^{(k+1)}} &\leftarrow {\vec{\beta}^{(k)}+({X}^T{W}{X})^{-1}{X}^T({y}-{p})}
\end{align*}

In [ ]:
beta = np.array([0.2, 0.1, 0.1]).reshape(-1, 1) # Initialize beta

In [ ]:
print(beta)

#### Initialize the update value (set to be 1) for every iteration i.e.
$\Delta\beta=({X}^T{W}{X})^{-1}{X}^T({y}-{p})$


In [33]:
Deltabeta= np.array([0.1, 0.1, 0.1]).reshape(-1, 1)

In [34]:
Deltabeta

array([[0.1],
       [0.1],
       [0.1]])

In [35]:
while np.sum(np.abs(Deltabeta))>1e-15:
    p=1/(1+np.exp(-np.matmul(X, beta))) #calculates the estimated probability
    W=np.diag(np.multiply(p,(1-p))[:,0])
    XtWX=np.matmul(np.matmul(X.T, W), X) #Hessian Matrix
    XtY=np.matmul(X.T, (y-p))
    Deltabeta=np.matmul(np.linalg.inv(XtWX), XtY)
    beta=beta+Deltabeta
print(beta.T)

[[0.40797669 0.09767266 1.27640957]]


In [ ]:
p=1/(1+np.exp(-np.matmul(X, beta)))

In [ ]:
W=np.diag(np.multiply(p,(1-p))[:,0])

#### Model Prediction

##### Prediction use home-made logistic regression model

In [36]:
1/(1+np.exp(-np.dot(beta.T, X[0])))

array([0.68362177])

##### Prediction use sklearn built-in logistic regression model

### Use sklearn package function 
```class sklearn.linear_model.LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)```

##### Memebers: coef_ ... et.c
##### Methods: fit(self, X, y[, sample_weight]) ... etc.

#### More Details https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

In [37]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(penalty='none', solver='newton-cg', fit_intercept=False)

lr.fit(X,y.reshape(y.size))

print([lr.coef_, lr.intercept_])

[array([[0.40797669, 0.09767266, 1.27640956]]), array([0.])]


In [40]:
lr.predict_proba(X[0:1])

array([[0.31637823, 0.68362177]])

In [41]:
np.sum(lr.predict_proba(X[0:1]))

1.0