## Document Classification

In [43]:
from gensim.test.utils import common_texts
from gensim.models import Word2Vec
import gensim.downloader as api
from gensim.models import TfidfModel
from gensim.corpora import Dictionary
import pandas as pd
from gensim.models import KeyedVectors
import numpy as np
import nltk
mt = pd.read_csv("Data/medicaltranscriptions.csv")
mt_token=[]
lenlist=[]
mt["description"]

0        A 23-year-old white female presents with comp...
1                Consult for laparoscopic gastric bypass.
2                Consult for laparoscopic gastric bypass.
3                                  2-D M-Mode. Doppler.  
4                                      2-D Echocardiogram
5        Morbid obesity.  Laparoscopic antecolic anteg...
6        Liposuction of the supraumbilical abdomen, re...
7                                      2-D Echocardiogram
8        Suction-assisted lipectomy - lipodystrophy of...
9                              Echocardiogram and Doppler
10       Morbid obesity.  Laparoscopic Roux-en-Y gastr...
11       Normal left ventricle, moderate biatrial enla...
12                 Cerebral Angiogram - moyamoya disease.
13       Patient presented to the bariatric surgery se...
14        Surgical removal of completely bony impacted...
15       Preoperative visit for weight management with...
16       Neck exploration; tracheostomy; urgent flexib...
17            

In [44]:
mt_token_nouns=[]
for i in range(len(mt["description"])):
    mt_token_pos=nltk.pos_tag(nltk.word_tokenize(mt["description"][i]))
    nouns = [word for word, pos in mt_token_pos if (pos == 'NN' or pos == 'NNP' or pos == 'NNS' or pos == 'NNPS')]
    mt_token_nouns = mt_token_nouns+nouns

In [47]:
mt_token

[]

In [48]:
mt_token_nouns_lower=[i.lower() for i in mt_token_nouns]
model = KeyedVectors.load_word2vec_format("Data/pubmed2018_w2v_200D/pubmed2018_w2v_200D.bin", binary=True)
# Access vectors for specific words with a keyed lookup:

In [49]:
model.similarity('allergy', 'allergic')

0.8360397

In [51]:
model['allergy']

array([ 0.19854781, -0.21359417,  0.49111918,  0.37198612,  0.02788076,
       -0.6640716 , -0.4250803 ,  0.28902203,  0.57635623, -0.22187796,
       -0.25903288, -0.7195324 ,  0.03803334,  0.3125623 ,  0.298701  ,
       -0.00505887, -0.35185388, -0.2890893 ,  0.20734306,  0.42626593,
       -0.28640017,  0.32212105,  0.02750463, -0.3123023 , -0.29028386,
       -0.03653466,  0.12400573,  0.09789123,  0.13039659, -0.4619009 ,
        0.27209795, -0.17449038,  0.23804636, -0.4312894 , -0.05130282,
       -0.32734397,  0.10837612, -0.3050455 ,  0.42598042, -0.04544117,
       -0.05461522,  0.09972726, -0.17839207,  0.091431  , -0.52221227,
        0.16877934,  0.23499149,  0.18054771,  0.16160291, -0.18967932,
       -0.22417451, -0.05054491,  0.307758  , -0.5508191 ,  0.19027798,
       -0.26564902, -0.33502126, -0.43869987,  0.11796953,  0.67479265,
       -0.10395984,  0.1835647 , -0.4174233 , -0.16568227, -0.1531111 ,
       -0.27356932,  0.4757376 ,  0.4521014 ,  0.11355381,  0.32

In [52]:
model.word_vec('allergy')

array([ 0.19854781, -0.21359417,  0.49111918,  0.37198612,  0.02788076,
       -0.6640716 , -0.4250803 ,  0.28902203,  0.57635623, -0.22187796,
       -0.25903288, -0.7195324 ,  0.03803334,  0.3125623 ,  0.298701  ,
       -0.00505887, -0.35185388, -0.2890893 ,  0.20734306,  0.42626593,
       -0.28640017,  0.32212105,  0.02750463, -0.3123023 , -0.29028386,
       -0.03653466,  0.12400573,  0.09789123,  0.13039659, -0.4619009 ,
        0.27209795, -0.17449038,  0.23804636, -0.4312894 , -0.05130282,
       -0.32734397,  0.10837612, -0.3050455 ,  0.42598042, -0.04544117,
       -0.05461522,  0.09972726, -0.17839207,  0.091431  , -0.52221227,
        0.16877934,  0.23499149,  0.18054771,  0.16160291, -0.18967932,
       -0.22417451, -0.05054491,  0.307758  , -0.5508191 ,  0.19027798,
       -0.26564902, -0.33502126, -0.43869987,  0.11796953,  0.67479265,
       -0.10395984,  0.1835647 , -0.4174233 , -0.16568227, -0.1531111 ,
       -0.27356932,  0.4757376 ,  0.4521014 ,  0.11355381,  0.32

In [53]:
description_vec=np.empty((0, 200), float)

for i in range(len(mt["description"])):
    word2vec_ls=np.empty((0, 200), float)
    mt_token_pos=nltk.pos_tag(nltk.word_tokenize(mt["description"][i]))
    for word, pos in mt_token_pos:
        if (pos == 'NN' or pos == 'NNP' or pos == 'NNS' or pos == 'NNPS'):
            try:
                word2vec_ls=np.vstack([word2vec_ls, model.word_vec(word)])
            except:
                pass
    if np.any(np.isnan(word2vec_ls)) or len(word2vec_ls)==0:
        desc_vec=np.zeros((1, 200))
    else:
        desc_vec = np.mean(word2vec_ls, axis=0).reshape(1, 200)
    description_vec=np.vstack([description_vec, desc_vec])

In [54]:
pd.DataFrame(description_vec)

0         1         2         3         4         5         6    \
0     0.060857  0.003464  0.233486 -0.013175  0.019383 -0.183592 -0.058973   
1     0.417814  0.528424  0.156247  0.314276 -0.028756 -0.003994 -0.286784   
2     0.417814  0.528424  0.156247  0.314276 -0.028756 -0.003994 -0.286784   
3     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5     0.014181  0.082424  0.294674  0.112812 -0.172921 -0.000093 -0.072514   
6    -0.035233  0.175767 -0.006637 -0.140653 -0.005438 -0.065982 -0.090176   
7     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8    -0.153898  0.225991 -0.120563  0.052349 -0.049304 -0.078558  0.058342   
9     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10    0.215244  0.146858  0.219157  0.494469 -0.141076  0.040542 -0.247104   
11    0.242823  0.053838 -0.098785  0.123731 -0.091107  0.155276  0.153408   
12    0.188915  0.285961 -0.251277 -0.005366 -0.556375  0.050706 -0.209796   
13    0.211850  0.288076  0.159685  0.252887 -0.002100  0.093448 -0.053655   
14   -0.443305 -0.035697 -0.160774 -0.107993  0.195320 -0.217185 -0.595953   
15    0.288709  0.350756  0.216138  0.383877 -0.066160 -0.189348 -0.263477   
16   -0.084082  0.166033 -0.060647  0.132419 -0.203503  0.083690 -0.246671   
17    0.095498  0.124678  0.104630  0.114710 -0.038268 -0.129482 -0.171379   
18   -0.060108  0.261561  0.160690 -0.055600 -0.101792  0.153241 -0.288987   
19   -0.000669  0.082423  0.140893  0.062199 -0.255712  0.059484 -0.194434   
20    0.057079  0.311567  0.054899  0.134766  0.020361 -0.235832  0.021038   
21    0.271508  0.416451  0.106090  0.528928 -0.166915  0.036609 -0.128929   
22    0.103634  0.721591  0.208995 -0.031896 -0.349519  0.218377 -0.590299   
23   -0.020617  0.049803  0.158462 -0.077581 -0.043854 -0.119857 -0.328270   
24   -0.087611  0.202687 -0.171525 -0.027119  0.041563 -0.331254 -0.256958   
25    0.103634  0.721591  0.208995 -0.031896 -0.349519  0.218377 -0.590299   
26   -0.073162  0.020905  0.013719 -0.048454 -0.307751 -0.133199 -0.259478   
27    0.261979  0.188107 -0.036017 -0.097946  0.003797 -0.086380 -0.324078   
28   -0.314084  0.190314 -0.055069  0.044720 -0.077237 -0.080055 -0.068202   
29   -0.205937  0.025623  0.039016 -0.079989 -0.030139 -0.175529 -0.165485   
...        ...       ...       ...       ...       ...       ...       ...   
4969  0.004841  0.279971 -0.023293  0.127243 -0.208987  0.053797 -0.105999   
4970 -0.086314  0.405420  0.035252  0.169189 -0.307020  0.012198 -0.261108   
4971  0.167904  0.477077 -0.240876  0.306166 -0.170208 -0.057673 -0.145601   
4972 -0.214645 -0.037340  0.009111  0.271296 -0.106311 -0.105760 -0.138046   
4973  0.047306  0.210227  0.141344  0.064212 -0.112280 -0.236735  0.083170   
4974 -0.111780  0.000124  0.124631  0.064836 -0.211778 -0.243173 -0.247799   
4975 -0.134988 -0.001891  0.021019  0.274712 -0.145869 -0.305823 -0.116801   
4976  0.127563  0.244622  0.035139  0.285237 -0.100770 -0.083078 -0.030074   
4977 -0.135041  0.198253  0.181668  0.287067 -0.013490 -0.177210  0.062529   
4978  0.056603  0.255601  0.178838  0.289405 -0.069494  0.119033  0.007544   
4979  0.417814  0.528424  0.156247  0.314276 -0.028756 -0.003994 -0.286784   
4980  0.070794  0.428558  0.233257  0.328910 -0.080782 -0.167032  0.003352   
4981 -0.070926  0.087520  0.052075 -0.026601 -0.174692 -0.066940 -0.125217   
4982  0.076978  0.183663  0.053097  0.115101  0.093175  0.443335  0.170184   
4983 -0.231182  0.150811  0.275072  0.311625 -0.199441 -0.207634 -0.070541   
4984 -0.134689  0.186803  0.309740  0.287916 -0.227710 -0.186539 -0.030226   
4985  0.045685  0.348826 -0.114995  0.357652 -0.063705  0.092950  0.013617   
4986 -0.256228 -0.133169  0.363215  0.097507 -0.318412 -0.257815 -0.271447   
4987 -0.150641  0.195537  0.256339 -0.092569 -0.177533 -0.207400 -0.180089   
4988  0.114508  0.066518  0.20858

In [55]:
from sklearn import preprocessing
from sklearn import svm
from sklearn.metrics import confusion_matrix
Doc2VecRep=pd.DataFrame(description_vec)

In [58]:
(np.unique(mt['medical_specialty']))

array([' Allergy / Immunology', ' Autopsy', ' Bariatrics',
       ' Cardiovascular / Pulmonary', ' Chiropractic',
       ' Consult - History and Phy.', ' Cosmetic / Plastic Surgery',
       ' Dentistry', ' Dermatology', ' Diets and Nutritions',
       ' Discharge Summary', ' ENT - Otolaryngology',
       ' Emergency Room Reports', ' Endocrinology', ' Gastroenterology',
       ' General Medicine', ' Hematology - Oncology',
       ' Hospice - Palliative Care', ' IME-QME-Work Comp etc.',
       ' Lab Medicine - Pathology', ' Letters', ' Nephrology',
       ' Neurology', ' Neurosurgery', ' Obstetrics / Gynecology',
       ' Office Notes', ' Ophthalmology', ' Orthopedic',
       ' Pain Management', ' Pediatrics - Neonatal',
       ' Physical Medicine - Rehab', ' Podiatry',
       ' Psychiatry / Psychology', ' Radiology', ' Rheumatology',
       ' SOAP / Chart / Progress Notes', ' Sleep Medicine',
       ' Speech - Language', ' Surgery', ' Urology'], dtype=object)

In [59]:
le = preprocessing.LabelEncoder()
le.fit(mt['medical_specialty'])

LabelEncoder()

In [61]:
y=le.transform(mt['medical_specialty'])

In [64]:
np.unique(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [67]:
le.inverse_transform([7])

array([' Dentistry'], dtype=object)

In [68]:
Doc2VecRep["y"] = y

In [69]:
Doc2VecRep

0         1         2         3         4         5         6  \
0     0.060857  0.003464  0.233486 -0.013175  0.019383 -0.183592 -0.058973   
1     0.417814  0.528424  0.156247  0.314276 -0.028756 -0.003994 -0.286784   
2     0.417814  0.528424  0.156247  0.314276 -0.028756 -0.003994 -0.286784   
3     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5     0.014181  0.082424  0.294674  0.112812 -0.172921 -0.000093 -0.072514   
6    -0.035233  0.175767 -0.006637 -0.140653 -0.005438 -0.065982 -0.090176   
7     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8    -0.153898  0.225991 -0.120563  0.052349 -0.049304 -0.078558  0.058342   
9     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10    0.215244  0.146858  0.219157  0.494469 -0.141076  0.040542 -0.247104   
11    0.242823  0.053838 -0.098785  0.123731 -0.091107  0.155276  0.153408   
12    0.188915  0.285961 -0.251277 -0.005366 -0.556375  0.050706 -0.209796   
13    0.211850  0.288076  0.159685  0.252887 -0.002100  0.093448 -0.053655   
14   -0.443305 -0.035697 -0.160774 -0.107993  0.195320 -0.217185 -0.595953   
15    0.288709  0.350756  0.216138  0.383877 -0.066160 -0.189348 -0.263477   
16   -0.084082  0.166033 -0.060647  0.132419 -0.203503  0.083690 -0.246671   
17    0.095498  0.124678  0.104630  0.114710 -0.038268 -0.129482 -0.171379   
18   -0.060108  0.261561  0.160690 -0.055600 -0.101792  0.153241 -0.288987   
19   -0.000669  0.082423  0.140893  0.062199 -0.255712  0.059484 -0.194434   
20    0.057079  0.311567  0.054899  0.134766  0.020361 -0.235832  0.021038   
21    0.271508  0.416451  0.106090  0.528928 -0.166915  0.036609 -0.128929   
22    0.103634  0.721591  0.208995 -0.031896 -0.349519  0.218377 -0.590299   
23   -0.020617  0.049803  0.158462 -0.077581 -0.043854 -0.119857 -0.328270   
24   -0.087611  0.202687 -0.171525 -0.027119  0.041563 -0.331254 -0.256958   
25    0.103634  0.721591  0.208995 -0.031896 -0.349519  0.218377 -0.590299   
26   -0.073162  0.020905  0.013719 -0.048454 -0.307751 -0.133199 -0.259478   
27    0.261979  0.188107 -0.036017 -0.097946  0.003797 -0.086380 -0.324078   
28   -0.314084  0.190314 -0.055069  0.044720 -0.077237 -0.080055 -0.068202   
29   -0.205937  0.025623  0.039016 -0.079989 -0.030139 -0.175529 -0.165485   
...        ...       ...       ...       ...       ...       ...       ...   
4969  0.004841  0.279971 -0.023293  0.127243 -0.208987  0.053797 -0.105999   
4970 -0.086314  0.405420  0.035252  0.169189 -0.307020  0.012198 -0.261108   
4971  0.167904  0.477077 -0.240876  0.306166 -0.170208 -0.057673 -0.145601   
4972 -0.214645 -0.037340  0.009111  0.271296 -0.106311 -0.105760 -0.138046   
4973  0.047306  0.210227  0.141344  0.064212 -0.112280 -0.236735  0.083170   
4974 -0.111780  0.000124  0.124631  0.064836 -0.211778 -0.243173 -0.247799   
4975 -0.134988 -0.001891  0.021019  0.274712 -0.145869 -0.305823 -0.116801   
4976  0.127563  0.244622  0.035139  0.285237 -0.100770 -0.083078 -0.030074   
4977 -0.135041  0.198253  0.181668  0.287067 -0.013490 -0.177210  0.062529   
4978  0.056603  0.255601  0.178838  0.289405 -0.069494  0.119033  0.007544   
4979  0.417814  0.528424  0.156247  0.314276 -0.028756 -0.003994 -0.286784   
4980  0.070794  0.428558  0.233257  0.328910 -0.080782 -0.167032  0.003352   
4981 -0.070926  0.087520  0.052075 -0.026601 -0.174692 -0.066940 -0.125217   
4982  0.076978  0.183663  0.053097  0.115101  0.093175  0.443335  0.170184   
4983 -0.231182  0.150811  0.275072  0.311625 -0.199441 -0.207634 -0.070541   
4984 -0.134689  0.186803  0.309740  0.287916 -0.227710 -0.186539 -0.030226   
4985  0.045685  0.348826 -0.114995  0.357652 -0.063705  0.092950  0.013617   
4986 -0.256228 -0.133169  0.363215  0.097507 -0.318412 -0.257815 -0.271447   
4987 -0.150641  0.195537  0.256339 -0.092569 -0.177533 -0.207400 -0.180089   
4988  0.114508  0.066518  0.208582 

## In sample prediction

In [70]:
clf = svm.SVC(kernel='linear')
clf.fit(Doc2VecRep.iloc[:, : 200], Doc2VecRep["y"])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [71]:
y_pred=pd.Series(clf.predict(Doc2VecRep.iloc[:, : 200]))

In [72]:
y_pred[0:10]

0     0
1     2
2     2
3    33
4    33
5     2
6    38
7    33
8     6
9    33
dtype: int64

In [73]:
y[0:10]

array([0, 2, 2, 3, 3, 2, 2, 3, 2, 3])

In [74]:
ConfusionM=confusion_matrix(np.array(y_pred), np.array(Doc2VecRep["y"]))

In [75]:
pd.DataFrame(ConfusionM)

0   1   2    3   4    5   6   7   8   9   ...  30  31  32  33  34  35  36  \
0    1   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   1   0   
1    0   8   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
2    0   0  14    0   0    9   0   0   0   0  ...   0   0   0   0   0   1   0   
3    0   0   0  215   0   44   0   0   0   0  ...   0   0   0  49   0  12   0   
4    0   0   0    0   4    0   0   0   0   0  ...   0   0   0   1   0   0   0   
5    3   0   1   31   1  276   0   4   5   9  ...   8   4  25  14   6  46   3   
6    0   0   1    0   0    1   3   0   0   0  ...   0   0   0   0   0   0   0   
7    0   0   0    0   0    1   0   9   0   0  ...   0   0   0   1   0   0   0   
8    0   0   0    0   0    1   0   0   7   0  ...   0   0   0   0   0   3   0   
9    0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
10   0   0   0    1   0    1   0   0   0   0  ...   1   0   0   0   0   0   0   
11   0   0   0    0   0    4   0   0   0   0  ...   0   0   0   1   0   1   0   
12   1   0   0    0   0    5   0   0   0   0  ...   1   0   0   1   0   0   0   
13   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   1   0   
14   0   0   0    0   0   17   0   0   0   0  ...   0   0   0   9   0   6   0   
15   1   0   0    4   0   30   0   0   0   0  ...   0   0   0   1   0   9   0   
16   0   0   0    2   0    9   0   0   0   0  ...   0   0   0   3   0  12   0   
17   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
18   0   0   0    0   3    0   0   0   0   0  ...   0   0   0   0   0   0   0   
19   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
20   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
21   0   0   0    0   0    3   0   0   0   0  ...   0   0   2   5   0   2   0   
22   0   0   0    0   0   21   0   0   0   0  ...   6   0   0  45   1   2   8   
23   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
24   0   0   0    0   0    6   0   0   0   0  ...   0   0   0  11   0   2   0   
25   0   0   0    1   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
26   0   0   0    0   0    3   0   0   0   0  ...   0   0   0   0   0   1   0   
27   0   0   0    0   6   29   0   0   0   0  ...   4  10   0  28   1  11   0   
28   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   3   0   0   0   
29   0   0   0    1   0    8   0   0   0   0  ...   0   0   0   1   0   0   0   
30   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   0   0   0   
31   0   0   0    0   0    1   0   0   0   0  ...   0  14   0   3   0   4   0   
32   0   0   0    0   0   10   0   0   0   0  ...   0   0  23   0   0   2   0   
33   0   0   0   28   0    6   0   0   0   0  ...   0   1   3  89   0   1   0   
34   0   0   0    0   0    0   0   0   0   0  ...   0   0   0   0   1   1   0   
35   1   0   0    4   0    2   0   0   3   1  ...   0   2   0   0   1  35   0   
36   0   0   0    1   0    1   0   0   0   0  ...   0   0   0   0   0   0   9   
37   0   0   0    0   0    1   0   0   0   0  ...   0   0   0   0   0   0   0   
38   0   0   2   84   0   12  24  14  14   0  ...   1  16   0   7   0   4   0   
39   0   0   0    0   0   15   0   0   0   0  ...   0   0   0   1   0   9   0   

    37   38  39  
0    0    0   0  
1    0    0   0  
2    0    2   0  
3    0   91   1  
4    0    0   0  
5    2   18  10  
6    0    2   0  
7    0    7   0  
8    0    2   0  
9    0    0   0  
10   0    0   0  
11   0   22   0  
12   0    0   1  
13   0    2   0  
14   0   76   1  
15   0    0   0  
16   0    7   0  
17   0    0   0  
18   0    0   0  
19   0    0   0  
20   0    0   1  
21   0    6   2  
22   0    7   0  
23   0    2   0  
24   0   48   0  
25   0    0   0  
26   0   29   0  
27   0  111   0  
28   0    6   0  
29   0    1   1  
30   0    0   0  
31   0    5   0  
32   0    0   0  
33   1   11   7  
34   0    0   0  
35   0    1   4  
36   0    0   0 

In [76]:
le.inverse_transform([38])

array([' Surgery'], dtype=object)

In [78]:
le.inverse_transform([27])

array([' Orthopedic'], dtype=object)

In [ ]:
np.diag(ConfusionM)

In [ ]:
np.sum(ConfusionM,  axis=0)

In [79]:
np.diag(ConfusionM)/np.sum(ConfusionM,  axis=0)

array([0.14285714, 1.        , 0.77777778, 0.57795699, 0.28571429,
       0.53488372, 0.11111111, 0.33333333, 0.24137931, 0.        ,
       0.07407407, 0.35714286, 0.24      , 0.15789474, 0.49130435,
       0.23552124, 0.35555556, 0.66666667, 0.1875    , 0.        ,
       0.17391304, 0.28395062, 0.41255605, 0.0212766 , 0.46875   ,
       0.03921569, 0.44578313, 0.53239437, 0.70967742, 0.15714286,
       0.        , 0.29787234, 0.43396226, 0.32600733, 0.1       ,
       0.21084337, 0.45      , 0.66666667, 0.5494107 , 0.43670886])

# Train-Test Split and Validation

In [ ]:
from sklearn.utils import shuffle
Doc2VecRepShuffle = shuffle(Doc2VecRep)