## Lecture 08 - Word representation, Term-Term Matrix, word2vec

### Install package 

```pip install nltk```

```pip install gensim```

In [1]:
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize, wordpunct_tokenize
from nltk.corpus import stopwords 
import nltk 

In [2]:
file = open("Data/J. K. Rowling - Harry Potter 1 - Sorcerer's Stone",'r')
harrypotter_corpus = file.read()

In [6]:
type(harrypotter_corpus)

str

### Document, Tokenization, Dictionary

In [7]:
#nltk.download('stopwords')
stop_words = set(stopwords.words('english')) 
print(stop_words)

{'yourself', 'she', 'wasn', 'how', 'yourselves', 'be', 'why', 'or', 'once', 'ain', 'from', 'about', "shan't", 'between', 'itself', 'if', "haven't", 'has', 'do', 'further', 'whom', 'some', 'll', 'd', 'they', 'hadn', 've', 'are', 'on', 'then', 'up', 'am', 'hers', "wasn't", "aren't", 'haven', 'their', 'theirs', 'own', 'you', 'all', 'when', 's', "shouldn't", 'into', 'its', 'and', 'the', 'i', 'won', 'he', 'ourselves', 'have', 'both', 'hasn', 'isn', 'did', 'her', 'off', 'while', 'who', 'not', 'will', 'does', 'yours', 'but', 'being', 'an', 'more', 'down', 'by', 'themselves', 'than', 'again', 'only', 'after', "isn't", 'because', 'under', 'very', 'o', 'that', 'each', 'don', "you'll", 'his', 'above', "it's", 'them', 'is', 'had', 'in', 'mightn', "you're", "should've", "mightn't", 'doing', 'any', "won't", "wouldn't", 'having', 'him', 'few', 'as', 'aren', "couldn't", 'mustn', 'most', 'here', 'such', 'we', 'now', 'couldn', 'to', "doesn't", "weren't", "don't", 're', 'been', "that'll", 'ma', 'our', 'm

In [10]:
#nltk.download('punkt')
word_tokens = wordpunct_tokenize(harrypotter_corpus)

In [15]:
word_tokens

['Harry',
 'Potter',
 'and',
 'the',
 'Sorcerer',
 "'",
 's',
 'Stone',
 'CHAPTER',
 'ONE',
 'THE',
 'BOY',
 'WHO',
 'LIVED',
 'Mr',
 '.',
 'and',
 'Mrs',
 '.',
 'Dursley',
 ',',
 'of',
 'number',
 'four',
 ',',
 'Privet',
 'Drive',
 ',',
 'were',
 'proud',
 'to',
 'say',
 'that',
 'they',
 'were',
 'perfectly',
 'normal',
 ',',
 'thank',
 'you',
 'very',
 'much',
 '.',
 'They',
 'were',
 'the',
 'last',
 'people',
 'you',
 "'",
 'd',
 'expect',
 'to',
 'be',
 'involved',
 'in',
 'anything',
 'strange',
 'or',
 'mysterious',
 ',',
 'because',
 'they',
 'just',
 'didn',
 "'",
 't',
 'hold',
 'with',
 'such',
 'nonsense',
 '.',
 'Mr',
 '.',
 'Dursley',
 'was',
 'the',
 'director',
 'of',
 'a',
 'firm',
 'called',
 'Grunnings',
 ',',
 'which',
 'made',
 'drills',
 '.',
 'He',
 'was',
 'a',
 'big',
 ',',
 'beefy',
 'man',
 'with',
 'hardly',
 'any',
 'neck',
 ',',
 'although',
 'he',
 'did',
 'have',
 'a',
 'very',
 'large',
 'mustache',
 '.',
 'Mrs',
 '.',
 'Dursley',
 'was',
 'thin',
 'a

In [16]:
word_tokens = [w.lower() for w in word_tokens] 
word_tokens = [w.lower() for w in word_tokens if not w in stop_words] 
word_tokens = [w.lower() for w in word_tokens if w.isalpha()] 

In [17]:
word_tokens

['harry',
 'potter',
 'sorcerer',
 'stone',
 'chapter',
 'one',
 'boy',
 'lived',
 'mr',
 'mrs',
 'dursley',
 'number',
 'four',
 'privet',
 'drive',
 'proud',
 'say',
 'perfectly',
 'normal',
 'thank',
 'much',
 'last',
 'people',
 'expect',
 'involved',
 'anything',
 'strange',
 'mysterious',
 'hold',
 'nonsense',
 'mr',
 'dursley',
 'director',
 'firm',
 'called',
 'grunnings',
 'made',
 'drills',
 'big',
 'beefy',
 'man',
 'hardly',
 'neck',
 'although',
 'large',
 'mustache',
 'mrs',
 'dursley',
 'thin',
 'blonde',
 'nearly',
 'twice',
 'usual',
 'amount',
 'neck',
 'came',
 'useful',
 'spent',
 'much',
 'time',
 'craning',
 'garden',
 'fences',
 'spying',
 'neighbors',
 'dursleys',
 'small',
 'son',
 'called',
 'dudley',
 'opinion',
 'finer',
 'boy',
 'anywhere',
 'dursleys',
 'everything',
 'wanted',
 'also',
 'secret',
 'greatest',
 'fear',
 'somebody',
 'would',
 'discover',
 'think',
 'could',
 'bear',
 'anyone',
 'found',
 'potters',
 'mrs',
 'potter',
 'mrs',
 'dursley',
 '

In [19]:
len(word_tokens)

40762

In [20]:
vocab = set(word_tokens)

In [22]:
len(vocab)

5615

In [23]:
vocab

{'rubber',
 'ushered',
 'limp',
 'drumming',
 'smoother',
 'firelight',
 'awkwardly',
 'spiny',
 'paint',
 'cafru',
 'cringed',
 'remarkably',
 'discuss',
 'currently',
 'hood',
 'cleared',
 'arrangements',
 'bald',
 'aloud',
 'awaiting',
 'somewhere',
 'tapdance',
 'putted',
 'chuckled',
 'street',
 'awful',
 'examine',
 'skinny',
 'pomftey',
 'helping',
 'animals',
 'monk',
 'gains',
 'shoulders',
 'mid',
 'easiest',
 'howard',
 'ambition',
 'hoops',
 'flocking',
 'muscle',
 'walnut',
 'hermlone',
 'anxiously',
 'animal',
 'among',
 'ray',
 'plays',
 'figg',
 'desk',
 'deputy',
 'agony',
 'painful',
 'deadly',
 'courtyard',
 'ping',
 'whimper',
 'shore',
 'whelk',
 'deaths',
 'start',
 'spear',
 'coulda',
 'toasting',
 'rip',
 'dive',
 'airplane',
 'ter',
 'students',
 'c',
 'thronging',
 'break',
 'upon',
 'bravely',
 'slytherins',
 'buy',
 'yorkshire',
 'pork',
 'chattering',
 'hungrily',
 'fouls',
 'thern',
 'wriggles',
 'tying',
 'midst',
 'humans',
 'steady',
 'notices',
 'sally

In [24]:
char_to_int = dict((c,i) for i,c in enumerate(vocab))
int_to_char = dict((i,c) for i,c in enumerate(vocab))

In [25]:
char_to_int['harry']

3546

In [26]:
int_to_char[3546]

'harry'

In [28]:
X = np.zeros((len(word_tokens), len(vocab)))
window_size = 5
for i, word in enumerate(word_tokens):
    isetvalue=0
    w2v=np.zeros(len(vocab))
    for icontext in range(max(i-window_size,0), min(i+window_size, len(word_tokens)-1)+1):
        if icontext!=i:
            w2v[char_to_int[word_tokens[icontext]]]=w2v[char_to_int[word_tokens[icontext]]]+1
    X[i]=w2v

In [37]:
sum(X[20])

10.0

In [38]:
np.nonzero(X[0])

(array([1529, 3028, 4263, 5156, 5393]),)

In [42]:
int_to_char[5156]

'one'

In [43]:
X.shape

(40762, 5615)

In [ ]:
word_tokens[0:10]

In [45]:
colnames=[int_to_char[i] for i in range(len(vocab))]

In [ ]:
colnames

In [48]:
word2vecrep=pd.DataFrame(X, columns=colnames)

In [54]:
word2vecrep

rubber  ushered  limp  drumming  smoother  firelight  awkwardly  spiny  \
0         0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
1         0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
2         0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
3         0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
4         0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
...       ...      ...   ...       ...       ...        ...        ...    ...   
40757     0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
40758     0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
40759     0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
40760     0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   
40761     0.0      0.0   0.0       0.0       0.0        0.0        0.0    0.0   

       paint  cafru  ...  sweltering  jinx  abysmal  belonging  trees  tape  \
0        0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
1        0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
2        0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
3        0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
4        0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
...      ...    ...  ...         ...   ...      ...        ...    ...   ...   
40757    0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
40758    0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
40759    0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
40760    0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   
40761    0.0    0.0  ...         0.0   0.0      0.0        0.0    0.0   0.0   

       frog  breathe  trophy  mon  
0       0.0      0.0     0.0  0.0  
1       0.0      0.0     0.0  0.0  
2       0.0      0.0     0.0  0.0  
3       0.0      0.0     0.0  0.0  
4       0.0      0.0     0.0  0.0  
...     ...      ...     ...  ...  
40757   0.0      0.0     0.0  0.0  
40758   0.0      0.0     0.0  0.0  
40759   0.0      0.0     0.0  0.0  
40760   0.0      0.0     0.0  0.0  
40761   0.0      0.0     0.0  0.0  

[40762 rows x 5615 columns]

In [55]:
word2vecrep["wordkey"]=word_tokens

In [56]:
word2vecrep["wordkey"]

0           harry
1          potter
2        sorcerer
3           stone
4         chapter
           ...   
40757         lot
40758         fun
40759      dudley
40760      summer
40761         end
Name: wordkey, Length: 40762, dtype: object

In [57]:
word2vecbycount=word2vecrep.groupby(['wordkey']).sum()

In [59]:
word2vecbycount

rubber  ushered  limp  drumming  smoother  firelight  \
wordkey                                                               
aaaaaaaaaargh     0.0      0.0   0.0       0.0       0.0        0.0   
aaaargh           0.0      0.0   0.0       0.0       0.0        0.0   
aaah              0.0      0.0   0.0       0.0       0.0        0.0   
aargh             0.0      0.0   0.0       0.0       0.0        0.0   
aback             0.0      0.0   0.0       0.0       0.0        0.0   
...               ...      ...   ...       ...       ...        ...   
zombie            0.0      0.0   0.0       0.0       0.0        0.0   
zoo               0.0      0.0   0.0       0.0       0.0        0.0   
zoom              0.0      0.0   0.0       0.0       0.0        0.0   
zoomed            0.0      0.0   0.0       0.0       0.0        0.0   
zooming           0.0      0.0   0.0       0.0       0.0        0.0   

               awkwardly  spiny  paint  cafru  ...  sweltering  jinx  abysmal  \
wordkey                                        ...                              
aaaaaaaaaargh        0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
aaaargh              0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
aaah                 0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
aargh                0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
aback                0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
...                  ...    ...    ...    ...  ...         ...   ...      ...   
zombie               0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
zoo                  0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
zoom                 0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
zoomed               0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   
zooming              0.0    0.0    0.0    0.0  ...         0.0   0.0      0.0   

               belonging  trees  tape  frog  breathe  trophy  mon  
wordkey                                                            
aaaaaaaaaargh        0.0    0.0   0.0   0.0      0.0     0.0  0.0  
aaaargh              0.0    0.0   0.0   0.0      0.0     0.0  0.0  
aaah                 0.0    0.0   0.0   0.0      0.0     0.0  0.0  
aargh                0.0    0.0   0.0   0.0      0.0     0.0  0.0  
aback                0.0    0.0   0.0   0.0      0.0     0.0  0.0  
...                  ...    ...   ...   ...      ...     ...  ...  
zombie               0.0    0.0   0.0   0.0      0.0     0.0  0.0  
zoo                  0.0    0.0   0.0   0.0      0.0     0.0  0.0  
zoom                 0.0    0.0   0.0   0.0      0.0     0.0  0.0  
zoomed               0.0    0.0   0.0   0.0      0.0     0.0  0.0  
zooming              0.0    0.0   0.0   0.0      0.0     0.0  0.0  

[5615 rows x 5615 columns]

In [73]:
word2vecbycount.loc["harry", 'potter']

68.0

In [75]:
word2vecbycount.loc["potter", 'harry']

68.0

In [76]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([np.array(word2vecbycount.loc["harry", :])], [np.array(word2vecbycount.loc["wand", :])])

array([[0.63121011]])

In [78]:
cosine_similarity([np.array(word2vecbycount.loc["harry", :])], [np.array(word2vecbycount.loc["potter", :])])

array([[0.67016778]])

In [ ]:
for i in np.nonzero(X[0])[0]:
    print(colnames[i])
    print(X[0][i])

### Gensim pretrained-word2vec methods

### pretrained word2vec model documentation
https://github.com/RaRe-Technologies/gensim-data

In [79]:
from gensim.models import KeyedVectors
import gensim.downloader as api
print(api.load("word2vec-google-news-300", return_path=True))
# When you use the Gensim download API, all data is stored in your `~/gensim-data` home folder.

/Users/dlai/gensim-data/word2vec-google-news-300/word2vec-google-news-300.gz


In [81]:
model = KeyedVectors.load_word2vec_format('/Users/dlai/gensim-data/word2vec-google-news-300/word2vec-google-news-300.gz', binary=True)

In [85]:
len(model["finance"])

300

In [86]:
print(model.similarity('allergy', 'allergic'))
print(model.similarity('harry', 'potter'))
print(model.similarity('water', 'fluid'))
print(model.similarity('finance', 'financial'))

0.71326107
0.08543932
0.34774813
0.49127555


### Word Relationship
#### $\vec{best}-\vec{good} \sim \vec{worst}-\vec{bad}$
#### $\vec{best}-\vec{good}+\vec{bad} \sim \vec{worst}$

In [87]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
v1=np.array(model['best']-model['good']+model['bad'])
v2=np.array(model['worst'])
cosine_similarity([v1], [v2])

array([[0.6791442]], dtype=float32)